/**
 * Template 02 — Consumer Contract: POST /users (Create)
 * What: Tests POST /users — verifies provider creates user and validates body matchers.
 * Why: Teaches POST with JSON body, regex for email format, eachLike for arrays.
 * Where: companion_files/pact-templates/template-02-consumer-contract-create.test.js
 *
 * How to run: npx jest template-02-consumer-contract-create.test.js --runInBand
 * Expected: PASS + pacts/WebApp-UserAPI.json now has 2+ interactions
 * What if: 201 vs 200 → provider must return 201 for creation, check willRespondWith status
 * What's next: Template 03 — GET with query params (template-03)
 */

const path = require('path');
const { PactV3, MatchersV3 } = require('@pact-foundation/pact');
const axios = require('axios');

const { like, integer, string, regex, eachLike, boolean } = MatchersV3;

const provider = new PactV3({
  consumer: 'WebApp',
  provider: 'UserAPI',
  dir: path.resolve(process.cwd(), 'pacts'),
  logLevel: 'warn',
});

describe('Consumer Contract — POST /users (Create)', () => {
  it('creates a new user and returns 201 with generated id', async () => {
    provider
      .given('no user with email bob.new@example.com exists')
      .uponReceiving('a request to create a new user')
      .withRequest({
        method: 'POST',
        path: '/users',
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: {
          name: string('Bob Smith'),
          email: regex('^[^@]+@[^@]+\\.[^@]+$', 'bob.new@example.com'),
          tags: eachLike('developer', 1),
        },
      })
      .willRespondWith({
        status: 201,
        headers: { 'Content-Type': 'application/json' },
        body: {
          id: integer(6),
          name: string('Bob Smith'),
          email: regex('^[^@]+@[^@]+\\.[^@]+$', 'bob.new@example.com'),
          active: boolean(true),
          // createdAt is generated by provider — we only check it exists and is a string
          tags: eachLike('developer', 1),
        },
      });

    await provider.executeTest(async (mockServer) => {
      const res = await axios.post(
        `${mockServer.url}/users`,
        {
          name: 'Bob Smith',
          email: 'bob.new@example.com',
          tags: ['developer'],
        },
        {
          headers: { 'Content-Type': 'application/json', Accept: 'application/json' },
          validateStatus: () => true,
        }
      );

      expect(res.status).toBe(201);
      expect(res.data.id).toBeDefined();
      expect(typeof res.data.id).toBe('number');
      expect(res.data.name).toBe('Bob Smith');
      expect(res.data.email).toMatch(/^[^@]+@[^@]+\.[^@]+$/);
      expect(res.data.tags).toBeInstanceOf(Array);
    });
  });

  it('creates user with minimal body — tags defaulted by provider', async () => {
    // Why regex? Without it, like('bob@example.com') would pass even if provider
    // returns "not-an-email". Regex enforces FORMAT, not just type.
    provider
      .given('user creation with minimal fields')
      .uponReceiving('a request to create user with only name and email')
      .withRequest({
        method: 'POST',
        path: '/users',
        headers: { 'Content-Type': 'application/json' },
        body: {
          name: like('Evan Stone'),
          email: regex('^[^@]+@[^@]+\\.[^@]+$', 'evan@example.com'),
        },
      })
      .willRespondWith({
        status: 201,
        headers: { 'Content-Type': 'application/json' },
        body: {
          id: integer(7),
          name: like('Evan Stone'),
          email: regex('^[^@]+@[^@]+\\.[^@]+$', 'evan@example.com'),
          active: boolean(true),
          tags: eachLike('viewer', 1),
        },
      });

    await provider.executeTest(async (mockServer) => {
      const res = await axios.post(
        `${mockServer.url}/users`,
        { name: 'Evan Stone', email: 'evan@example.com' },
        { headers: { 'Content-Type': 'application/json' }, validateStatus: () => true }
      );
      expect(res.status).toBe(201);
      expect(res.data.id).toBeDefined();
    });
  });
});
