/**
 * Template 05 — Provider Verification (Verifier + stateHandlers)
 * What: Verifies REAL provider (Express at http://localhost:3000) satisfies all consumer pacts.
 * Why: The other half of contract testing — consumer defines contract, provider proves it can satisfy.
 * Where: companion_files/pact-templates/template-05-provider-verification.test.js
 *
 * How to run:
 *   1. Start provider:  npm start  (in contract-mock-demo-app, port 3000)
 *   2. Generate pacts:  npx jest template-0[1-4] --runInBand  (creates pacts/WebApp-UserAPI.json)
 *   3. Verify:         npx jest template-05-provider-verification.test.js --runInBand
 *   Expected: "Pact Verification Complete!" + all interactions PASS
 *   If provider breaks contract → FAIL with diff (expected vs actual)
 *
 * What you should see: "Pact Verification Complete!" + PASS
 * What if: ECONNREFUSED → provider not running (npm start in Terminal 1)
 *          Pact file not found → run templates 01-04 first
 * What's next: Run all 5 together (npm test) + inspect pact JSON (see PDF p18)
 *
 * Stack: Pact 17.1.3 Verifier + Jest 29 + Node 18+
 * Verified: 2026-09-04 against docs.pact.io + github.com/pact-foundation/pact-js
 */

const path = require('path');
const { Verifier } = require('@pact-foundation/pact');

// ── Config ──────────────────────────────────────────────────────────────
// What: Verifier checks real provider against pact JSON generated by consumer tests.
// Why: CI gate — blocks deploy if provider breaks contract.
// Where: providerBaseUrl = running provider, pactUrls = generated pact files.
const PROVIDER_BASE_URL = process.env.PROVIDER_BASE_URL || 'http://localhost:3000';
const PACT_FILE = path.resolve(process.cwd(), 'pacts', 'WebApp-UserAPI.json');
const PACT_FILE_ALT = path.resolve(__dirname, '..', 'contract-mock-demo-app', 'pacts', 'WebApp-UserAPI.json');
const fs = require('fs');

function resolvePactUrls() {
  const candidates = [PACT_FILE, PACT_FILE_ALT, path.resolve(process.cwd(), '..', 'contract-mock-demo-app', 'pacts', 'WebApp-UserAPI.json')];
  const found = candidates.filter(p => fs.existsSync(p));
  if (found.length > 0) return found;
  // Return primary even if not found — Verifier will give clear error
  return [PACT_FILE];
}

describe('Provider Verification — UserAPI satisfies WebApp contracts', () => {
  // Increase timeout — provider verification hits real HTTP
  jest.setTimeout(30000);

  it('validates provider against consumer pacts', async () => {
    const pactUrls = resolvePactUrls();

    // Pre-check: pact file must exist
    const missing = pactUrls.filter(p => !fs.existsSync(p));
    if (missing.length === pactUrls.length) {
      console.warn(`\n[WARN] No pact file found at: ${pactUrls.join(', ')}`);
      console.warn('Run consumer tests first: npx jest template-0[1-4] --runInBand\n');
    }

    const verifier = new Verifier({
      provider: 'UserAPI',
      providerBaseUrl: PROVIDER_BASE_URL,
      pactUrls,
      // ── Provider States ─────────────────────────────────────────────
      // What: given('user with id 1 exists') in consumer test → this handler seeds data.
      // Why: Provider must be in correct state before each interaction is verified.
      // Analogy: like setting up the stage before each scene in a play.
      stateHandlers: {
        'user with id 1 exists': async () => {
          // In real provider: seed DB with user 1
          // Demo provider already has seed data — just confirm
          return Promise.resolve({ description: 'user 1 seeded (demo has 5 users)' });
        },
        'user with id 2 exists': async () => Promise.resolve({ description: 'user 2 exists' }),
        'no user with email bob.new@example.com exists': async () => Promise.resolve({ description: 'ensure bob.new not exists' }),
        'user creation with minimal fields': async () => Promise.resolve({ description: 'ready for minimal create' }),
        'users matching alice exist': async () => Promise.resolve({ description: 'alice users seeded' }),
        'no users matching xyznotfound exist': async () => Promise.resolve({ description: 'no xyznotfound users' }),
        'at least 11 users exist for pagination': async () => Promise.resolve({ description: 'pagination data ready (legacy)' }),
        'users exist for pagination': async () => Promise.resolve({ description: 'pagination data ready' }),
        'no user with id 999 exists': async () => Promise.resolve({ description: 'ensure 999 not exists' }),
        'user creation validation is enforced': async () => Promise.resolve({ description: 'validation enabled' }),
        'user creation requires name': async () => Promise.resolve({ description: 'name required' }),
      },
      // Optional: add auth header if provider requires it
      // requestFilter: (req, res, next) => { req.headers['Authorization'] = 'Bearer test-token'; next(); },
      logLevel: 'warn',
    });

    // verifyProvider() — hits real provider, checks each interaction, reports diff on failure
    const output = await verifier.verifyProvider();
    // If we reach here, all interactions passed
    expect(output).toBeDefined();
    console.log('\n[Pact] Verification Complete — provider satisfies all consumer contracts!\n');
  });
});
